name: CI(Continuous Integration)

on:
  push:
    branches: [ main ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

env:
  PUBLIC_API_BASE: ${{ secrets.PUBLIC_API_BASE }} #读生产环境的api地址

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
  
  check-and-build:
    needs: lint # 等lint 过了再检查
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Fuwari
        uses: actions/checkout@v4
        with:
          path: fuwari
      - name: Checkout Posts
        uses: actions/checkout@v4
        with:
          repository: cannian16/posts
          token: ${{ secrets.POSTS_TOKEN }}
          path: posts
      
      - name: Sync Posts to Theme
        run: |
          rm -rf fuwari/src/content/posts
          mkdir -p fuwari/src/content/posts
          cp -r posts/* fuwari/src/content/posts/
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'fuwari/pnpm-lock.yaml'
      
      - name: Install Dependencies
        working-directory: ./fuwari
        run: pnpm install --frozen-lockfile
      - name: Type Check
        working-directory: ./fuwari
        run: pnpm astro check
      - name: Production Build
        working-directory: ./fuwari
        run: pnpm astro build && pnpm pagefind --site dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist               # 产物的名字（下载时要用同样的名字）
          path: fuwari/dist/