name: CI(Continuous Integration)

on:
  push:
    branches: [ main ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
  
  check-and-build:
    needs: lint # 等lint 过了再检查
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4 
      - name: Setup pnpm
        uses: pnpm/action-setup@v4 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Type Check
        run: pnpm astro check
      - name: Production Build
        run: pnpm astro build